version: '3.8'

services:
  web:
    build: .
    restart: always
#    volumes:
#      - ./ :/usr/src/app/
    ports:
      - 8080:8080
    command: gunicorn --bind 0.0.0.0:8080 main_app:app

  nginx:
    build: ./services/nginx
    ports:
      - 80:80
    depends_on:
      - web